name: ScoreboardDB
main: me.mklv.scoreboarddb.ScoreboardDBPlugin
version: 1.0
api-version: 1.20
commands:
  scoreboarddb:
    aliases: [sbdb]
    description: Main command for ScoreboardDBPlugin
    usage: /<command> <save|get|sync-now> [args]
    permission: scoreboarddb.use
