name: ScoreboardDB
main: me.mklv.scoreboarddb.ScoreboardDBPlugin
version: ${version}
api-version: "1.20"
authors:
  - IceVallish / Suskese
folia-supported: true
softdepend:
  - PlaceholderAPI
commands:
  scoreboarddb:
    aliases: [sbdb]
    description: Main command for ScoreboardDB
    usage: /<command> <push|pull|sync-now|get|refresh-cache> [args]
