name: ScoreboardDB
main: me.mklv.scoreboarddb.ScoreboardDBPlugin
version: ${version}
api-version: 1.20
folia-supported: true
commands:
  scoreboarddb:
    aliases: [sbdb]
    description: Main command for ScoreboardDB
    usage: /<command> <save|get|sync-now> [args]
    permission: scoreboarddb.use
